---
title: "Introduction and Background"
description: |
  Explaining who I am and what the work I do is.
author:
  - name: Gerard Causse
    url: https://example.com/norajones
date: 2022-12-13
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
Hello and welcome to my blog. My name is Gerard Causse, and this blog covers the projects I have been working on for EPRI, the Electrical Power Research Institute, the company I work for. these projects combined are my senior project, and I have been working on them full time since September 2022.

To give you some background, I am a senior at Brigham Young University – Idaho majoring in Data Science. Back in April of 2022 I was hired as an intern at EPRI as a data science/programming student employee. The Electrical Power Research Institute, (EPRI), is a non-profit company that does research for and on the power plants around the country. Companies interested in the research done by EPRI can help fund their research, and in exchange, receive the results of this study. 

EPRI does research into many components of power generation, including nuclear power, the low carbon research initiative, technological innovation, and many more. I work for the Materials and Repair section of the Generation group, and so most of the work I do involves analyzing the data we collect from the materials used in power plants and provide insights on how long they can last and what repair options are available.

As mentioned earlier, I work as a programmer here, and a lot of what I do here is develop web-based tools that would allow engineers and workers at power plants to perform calculations based on their needs for specific problems. These tools are written in Python and are made available online using a module called Streamlit.

When working with websites and web tools, generally a developer would need to know how to write HTML, CSS, and JavaScript code. But a lot of data science work is done with Python which wasn’t designed for working on websites. What Streamlit does is allow a Python developer to write a script that will then be converted into a web page using HTML, CSS, and JavaScript. Normally websites need to be given structure by HTML, made pretty by CSS, and made interactable with JavaScript. These will then communicate with a backend of some sort, often Java, to receive instructions on how to handle user input as fetch additional information when needed. Streamlit basically allows me to do all of this with just Python.  These Python scripts will be run every time the user interacts with the page, (clicking a button, for example). In a way, you can think of Streamlit as a full stack development all-in-one tool. 

And so, my work here was to write Python scripts that could be rerun quickly and efficiently to allow the user to interact with the webpages while also displaying graphs or calculations or whatever else the webpage needs to help the user out. The rest of the posts on this blog will go into detail for the tools I have developed or helped to develop in my time here.




<!-- Learn more about using Distill at <https://rstudio.github.io/distill>. -->


